pool:
  name: Azure Pipelines
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: AzureFileCopy@3
  displayName: 'AzureBlob File Copy'
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/ramarao3.stack/drop'
    azureSubscription: ramasc
    Destination: AzureBlob
    storage: ramastorageacc
    ContainerName: test
    AdditionalArgumentsForBlobCopy: '--blob-tags=''version=features'''
    sasTokenTimeOutInMinutes: 240